@baseUrl = http://localhost:3000

### show recados
GET {{baseUrl}}/recados
### show one recados
GET {{baseUrl}}/recados/2

### Create new recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "Novo Recado",
    "de": "Joana",
    "para": "João"
}

### Atualiza um recado
PATCH {{baseUrl}}/recados/2
Content-Type: application/json

{
    "texto": "ATUALIZAR Recado",
    "lido": true
}

###
DELETE  {{baseUrl}}/recados/2