@baseUrl = http://localhost:3000

### show recados
GET {{baseUrl}}/recados

### show one recados
GET {{baseUrl}}/recados/1

### Create new recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "recado": "this is recad send!",
  "new key": "outher value"
}

### Atualiza um recado
PATCH {{baseUrl}}/recados/1
Content-Type: application/json

{
  "recado": "Este é o recado que estou enviando!"
}